In [1]:
import numpy as np

In [3]:
# zero array
np.zeros(4)

array([0., 0., 0., 0.])

In [4]:
#array with ones

np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [5]:
# array with empty (random numbers)

np.empty((5,5))

array([[4.67296746e-307, 1.69121096e-306, 1.95821031e-306,
        7.56587584e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306],
       [1.33510679e-306, 2.22522597e-306, 1.33511018e-306,
        6.23057689e-307, 1.33511290e-306],
       [1.78019082e-306, 8.45559303e-307, 8.06613465e-308,
        6.89810244e-307, 1.22387550e-307],
       [2.22522596e-306, 8.34423917e-308, 9.79107193e-307,
        1.02353398e-306, 2.10077583e-312]])

In [9]:
#array with arange
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
#array with equal intervals

np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])