In [1]:
import numpy as np

In [3]:
# Basic Operations Example

first_trial_cyclist=[10,15,17,26]
second_trial_cyclist=[12,11,21,24]

In [4]:
np_first_trial_cyclist=np.array(first_trial_cyclist)
np_second_trial_cyclist=np.array(second_trial_cyclist)

In [5]:
#Total distance
np_total_distance=np_first_trial_cyclist+np_second_trial_cyclist
np_total_distance

array([22, 26, 38, 50])

In [6]:
# Mathematical Operations

#addition

np.add(2,3)

5

In [7]:
#Subtraction
np.subtract(45,23)

22

In [8]:
#ndarray multiplication
#create ndarray which contains number of hours worked for 5 days
#hourly rate is 15 USD
np_daily_wage=np.array([7,9,13,8,11])*15
np_daily_wage


array([105, 135, 195, 120, 165])

In [9]:
# total earnings after 5 days
np.sum(np_daily_wage)

720

In [10]:
#Comparison Operators
# create ndarray for weekly hrs, 5 consecutive weeks hrs data
np_weekly_hrs=np.array([23,41,55,47,38])

In [11]:
#week with more than 40 hrs

np_weekly_hrs[np_weekly_hrs>40]

array([41, 55, 47])

In [12]:
#Logical Operations (Generates Boolean arrays)
#AND
np.logical_and(np_weekly_hrs>20,np_weekly_hrs<50)

array([ True,  True, False,  True,  True])

In [15]:
# Logical Not 
np.logical_not(np_weekly_hrs>40)

array([ True, False, False, False,  True])

In [17]:
# Accessing elements
cyclist_trials=np.array([[10,15,17,26],[12,11,21,24]])

first_cyclist=cyclist_trials[0]
first_cyclist

array([10, 15, 17, 26])

In [18]:
second_cyclist=cyclist_trials[1]
second_cyclist

array([12, 11, 21, 24])

In [19]:
first_cyclist_all_trials=cyclist_trials[:,0]
first_cyclist_all_trials

array([10, 12])

In [20]:
# slicing to get 15,17,11,21

cyclist_trials

array([[10, 15, 17, 26],
       [12, 11, 21, 24]])

In [21]:
cyclist_trials.shape # 2 rows, 4 columns

(2, 4)

In [22]:
cyclist_trials[:,1:3]

array([[15, 17],
       [11, 21]])

In [23]:
# iterating through dataset

for elem in cyclist_trials:
    print(elem)

[10 15 17 26]
[12 11 21 24]


In [24]:
# Indexing with Boolean arrays
test_scores=np.array([[83,71,57,63],[54,68,81,45]])

In [25]:
passing_score=test_scores>60

In [26]:
test_scores[passing_score]

array([83, 71, 63, 68, 81])

In [27]:
test_scores=np.array([[83,71,57,63],[54,68,81,45]])
passing_score=test_scores>60
test_scores[passing_score]

array([83, 71, 63, 68, 81])